name: Test Conda setup action

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  example-unix:
    name: Example (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/action-setup-conda@develop
        with:
          miniconda-version: 'latest'
          activate-environment: 'test'
          environment-file: etc/example-environment.yml
          python-version: 3.6
          auto-activate-base: true
          auto-update-conda: false
      - name: Base environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
          printenv | sort
      - name: Bash check
        shell: bash -l {0}
        run: |
          conda info
          conda list
          printenv | sort
      - name: Sh check
        shell: sh -l {0}
        run: |
          conda info
          conda list
          printenv | sort

  example-windows:
    name: Example Windows
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/action-setup-conda@develop
        with:
          miniconda-version: 'latest'
          activate-environment: 'test'
          environment-file: etc/example-environment.yml
          python-version: 3.6
          auto-activate-base: true
          auto-update-conda: false
      - run: cat C:\\Miniconda\\condabin\\conda_hook.bat
        shell: bash -l {0}
      - name: Base environment
        run: |
          conda info
          conda list
          printenv | sort
      - name: PowerShell check
        run: |
          conda info
          conda list
          gci env:* | sort-object name
      - name: PowerShell Core check
        shell: pwsh
        run: |
          conda info
          conda list
          gci env:* | sort-object name
      - name: Bash check
        shell: bash -l {0}
        run: |
          conda info
          conda list
          printenv | sort
      - name: Cmd.exe check
        shell: cmd /S /C "CALL "{0}""
        run: >-
          conda info &&
          conda list &&
          SET
