name: "Example 8: Catch invalid environment files"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  example-8:
    name: Ex8 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "2.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: setup-miniconda
        continue-on-error: true
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: etc/example-environment.yml
      - name: Check previous step failed
        shell: bash
        if: always()
        run: ${{ steps.setup-miniconda.outcome == 'failure' }}
