name: "Example 8: this should fail"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  example-8:
    name: Ex8 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "2.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: setup-miniconda
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: etc/example-faulty-environment.yml
      - name: Check previous step failed
        shell: bash
        run: ${{ steps.setup-miniconda.conclusion == 'failure' }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Environment
        shell: bash -l {0}
        run: printenv | sort
