name: "Example 6: Mamba"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  example-6:
    name: Ex6 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "2.7"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
          environment-file: etc/example-environment.yml
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - run: mamba install jupyterlab
