name: "Example 6: Mamba"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  example-6:
    name: Ex6 (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          python-version: "3.7"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
          environment-file: etc/example-environment.yml
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: Bash + NO .bat extension
        if: matrix.os == 'windows-latest'
        run: |
          conda --help || true
          /c/Miniconda/condabin/mamba --help || true
          mamba --help || true
          /c/Miniconda/condabin/conda --help || true
      - name: Bash + .bat extension
        if: matrix.os == 'windows-latest'
        run: |
          conda.bat --help || true
          /c/Miniconda/condabin/mamba.bat --help || true
          mamba.bat --help || true
          /c/Miniconda/condabin/conda.bat --help || true
      - name: CMD + NO .bat
        if: matrix.os == 'windows-latest'
        shell: cmd /C call {0}
        run: |
          conda --help
          C:\Miniconda\condabin\conda --help
          mamba --help
          C:\Miniconda\condabin\mamba --help
      - name: CMD + .bat
        if: matrix.os == 'windows-latest'
        shell: cmd /C call {0}
        run: |
          conda --help
          C:\Miniconda\condabin\conda.bat --help
          mamba.bat --help
          C:\Miniconda\condabin\mamba.bat --help
      - run: mamba install jupyterlab
