name: "Example 6: Mamba"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  example-6:
    name: Ex6 (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          python-version: "3.7"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
          environment-file: etc/example-environment.yml
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Universal call (= Windows, no .bat, from Bash)
        run: mamba --version

      - name: Windows, with .bat, from Bash
        if: matrix.os == 'windows-latest'
        run: mamba.bat --version

      - name: Windows, .bat, from Cmd
        shell: cmd /C call {0}
        if: matrix.os == 'windows-latest'
        run: mamba --version
      - name: Windows, no .bat, from Cmd
        shell: cmd /C call {0}
        if: matrix.os == 'windows-latest'
        run: mamba --version

      - name: Windows, .bat, from PowerShell
        shell: pwsh
        if: matrix.os == 'windows-latest'
        run: mamba.bat --version
      - name: Windows, no .bat, from PowerShell
        shell: pwsh
        if: matrix.os == 'windows-latest'
        run: mamba --version
