name: "Example 7: Explicit Environment Specification"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  example-7:
    name: Ex7 Explicit
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          auto-update-conda: false
          activate-environment: explicit-env
          environment-file: etc/example-explicit.${{ runner.os }}.conda.lock
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
