name: "Example 6: Mamba"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  example-6:
    name: Ex6 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "2.7"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
          environment-file: etc/example-environment.yml
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: windows debugging
        if: matrix.os == 'windows-latest'
        run: |
          set -x
          ls -al /c/Miniconda/condabin || true
          which mamba || true
          which mamba.bat || true
          /c/Miniconda/condabin/mamba --help || true
          mamba --help || true
          /c/Miniconda/condabin/mamba.bat --help || true
          mamba.bat --help || true
      - name: windows debugging 2
        if: matrix.os == 'windows-latest'
        shell: cmd /C call {0}
        run: |
          dir C:\Miniconda\condabin
          where mamba
          mamba --help
          C:\Miniconda\condabin\mamba --help
      - run: mamba install jupyterlab
