name: "Linting"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm check
          npm build
